// <auto-generated />
namespace SiADi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class virtual2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(virtual2));
        
        string IMigrationMetadata.Id
        {
            get { return "202011012129330_virtual2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
